config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'home/index'
  devise_for :overseers
 # devise_for :users
  devise_for :users, controllers: {registrations: 'users/registrations', sessions: 'users/sessions', passwords: 'users/passwords'}, path: 'users'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'home#index'

  namespace :users do
    resources :swish
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/overseer.rb
class Overseer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :trackable
end

app/models/swish.rb
class Swish < ApplicationRecord
  belongs_to :user
  has_many :swish_reports, dependent: :destroy

end

app/models/swish_report.rb
class SwishReport < ApplicationRecord
  has_one :swish

  def map_data_to_fields(data)
    self.accessibility ||= data['Accessibility'].to_f*100
    self.performance ||= data['Performance'].to_f*100
    self.pwa ||= data['PWA'].to_f*100
    self.seo ||= data['SEO'].to_f*100
    self.best_practices ||= data['Best-Practices'].to_f*100
    self.first_contentful_paint ||= data['First Contentful Paint']
    self.first_cpu_idle ||= data['First CPU Idle']
    self.first_meaningful_paint ||= data['First Meaningful Paint']
    self.estimated_input_latency ||= data['Estimated Input Latency']
    self.time_to_interactive ||= data['Time To Interactive']
    self.speed_index ||= data['Speed Index']
  end

  # Exclude password info from json output.
  def to_json(options = {})
    options[:except] ||= [:report, :id]
    super(options)
  end

  def to_h
    {
        "accessibility": self.accessibility,
        "performance": self.performance,
        "pwa": self.pwa,
        "seo": self.seo,
        "best_practices": self.best_practices,
        "first_contentful_paint": self.first_contentful_paint,
        "first_cpu_idle": self.first_cpu_idle,
        "first_meaningful_paint": self.first_meaningful_paint,
        "estimated_input_latency": self.estimated_input_latency,
        "time_to_interactive": self.time_to_interactive,
        "speed_index": self.speed_index
    }
  end

  def to_a
    [
        self.accessibility,
        self.performance,
        self.pwa,
        self.seo,
        self.best_practices,
        self.first_contentful_paint,
        self.first_cpu_idle,
        self.first_meaningful_paint,
        self.estimated_input_latency,
        self.time_to_interactive,
        self.speed_index
    ]
  end

  def self.describe(reports)
    reports_array = reports.map(&:to_a)

    df = Daru::DataFrame.new(reports_array);
    df = df.transpose

    df.describe([:count, :mean,:median, :min, :max]).transpose.to_h
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :trackable
  has_many :swishes, dependent: :nullify
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  private

  def set_flash(object, action, sentiment: :info, now: false)
    flash_hash = now ? flash.now : flash
    flash_hash[sentiment] = flash_message(object, action)
  end

  def set_flash_message(message, sentiment, now: false)
    flash_hash = now ? flash.now : flash
    flash_hash[sentiment] = message
  end

  def flash_message(object, action)
    class_name = object.class.name.titleize

    case action.to_sym
    when :create
      "#{class_name} has been successfully created."
    when :update
      "#{class_name} has been successfully updated."
    when :destroy
      "#{class_name} has been successfully destroyed."
    else
      "#{class_name} has been successfully changed."
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  layout 'shared/layouts/application'
  def index
  end
end

app/controllers/users/base_controller.rb
class Users::BaseController < ApplicationController
  include Pundit
  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
  protect_from_forgery

  layout 'users/layouts/application'
  before_action :authenticate_user!
  # before_action :set_paper_trail_whodunnit

  protected

  def policy!(user, record)
    CustomPolicyFinder.new(record, namespace).policy!.new(user, record)
  end

  def policy(record)
    policies[record] ||= policy!(pundit_user, record)
  end

  def pundit_policy_scope(scope)
    policy_scopes[scope] ||= policy_scope!(pundit_user, scope)
  end

  def policy_scope!(user, scope)
    CustomPolicyFinder.new(scope, namespace).scope!.new(user, scope).resolve
  end

  def pundit_user
    current_user
  end

  def namespace
    controller_namespace.classify.pluralize
  end

  def controller_namespace
    @controller_namespace ||= controller_path.split('/').first
  end


  private

  def info_for_paper_trail
    {whodunnit_type: current_user.class.name, whodunnit: current_user.id} if current_user.present?
  end

  def user_not_authorized
    message = 'You are not authorized to perform this action.'
    set_flash_message(message, :warning, now: false)
    redirect_to(request.referrer || user_root_path)
  end

  def render_pdf_for(record, params, locals = {})
    render(
        show_as_html: params[:debug].present?,
        pdf: record.filename,
        template: ['shared', 'layouts', 'pdf_templates', record.class.name.pluralize.underscore, 'show'].join('/'),
        layout: 'shared/layouts/pdf_templates/show',
        page_size: 'A4',
        footer: {
            center: '[page] of [topage]'
        },
        # show_as_html: true,
        locals: {
            record: record
        }.merge(locals)
    )
  end
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
  layout 'users/layouts/application'


  protected

    def after_resetting_password_path_for(resource_or_scope)
      sign_out(resource)
      new_user_session_path
    end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  layout 'users/layouts/application'

end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  layout 'users/layouts/application'

  def destroy
    signed_out = (Devise.sign_out_all_scopes ? sign_out : sign_out(resource_name))
    reset_session
    set_flash_message! :notice, :signed_out if signed_out
    yield if block_given?
    respond_to_on_destroy
  end

  private
  def after_sign_in_path_for(resource_or_scope)
    users_swish_index_path
  end

  def after_sign_out_path_for(resource_or_scope)
    new_user_session_path
  end
end

app/controllers/users/swish_controller.rb
class Users::SwishController < Users::BaseController
  before_action :set_swish, only: [:show]

  def index
    @swishes = Swish.all.where(user: current_user).reverse
  end

  def show
    @swish_reports = @swish.swish_reports.reverse.group_by(&:url)
    @swish_reports_description = {}
    @swish_reports.each do |url, report|
      @swish_reports_description[url] = SwishReport.describe(report)
    end
  end

  def create
    ::Services::SwishReport::SaveReport.new.call(params, current_user)
    render json: {"value": 2}, status: 200
  end

  private

  def set_swish
    @swish = Swish.find(params[:id])
  end

  attr_accessor :swish
end

app/helpers/application_helper.rb
module ApplicationHelper

end

app/helpers/display_helper.rb
module DisplayHelper
  def percentage_difference(new_value, previous_value)
    (((new_value.to_f - previous_value.to_f) / previous_value.to_f) * 100.0).round(2)
  end

  def difference_class(new_value, previous_value, inverse = false)
    difference = (new_value - previous_value)

    if difference.zero?
      return 'muted'
    end
    if inverse
      if (new_value - previous_value).negative?
        'success'
      else
        'danger'
      end
    else
      if (new_value - previous_value).negative?
        'danger'
      else
        'success'
      end
    end

  end

  def metric_with_change(report, metric, reports, index, prefix = '', inverse = false)
    last = index == (reports.length - 1)
    new_value = report.send(metric)
    old_value = last ? new_value : reports[index + 1].send(metric)
    [
        new_value,
        prefix,
        last ? '' : "<br><small ",
        last ? '' : "class='text-#{difference_class(new_value, old_value, inverse)}'>",
        last ? '' : " (#{percentage_difference(new_value, old_value)})</small>"
    ].join
  end

end

app/views/home/index.html.erb
<header class="masthead text-center text-white">
  <div class="masthead-content">
    <div class="container">
      <h1 class="masthead-heading mb-0">One Page Wonder</h1>
      <h2 class="masthead-subheading mb-0">Will Rock Your Socks Off</h2>
      <a href="#" class="btn btn-primary btn-xl rounded-pill mt-5">Learn More</a>
    </div>
  </div>
  <div class="bg-circle-1 bg-circle"></div>
  <div class="bg-circle-2 bg-circle"></div>
  <div class="bg-circle-3 bg-circle"></div>
  <div class="bg-circle-4 bg-circle"></div>
</header>

<section>
  <div class="container">
    <div class="row align-items-center">
      <div class="col-lg-6 order-lg-2">
        <div class="p-5">
          <img class="img-fluid rounded-circle" src="images/01.jpg" alt="">
        </div>
      </div>
      <div class="col-lg-6 order-lg-1">
        <div class="p-5">
          <h2 class="display-4">For those about to rock...</h2>
          <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quod aliquid, mollitia odio veniam sit iste esse assumenda amet aperiam exercitationem, ea animi blanditiis recusandae! Ratione voluptatum molestiae adipisci, beatae obcaecati.</p>
        </div>
      </div>
    </div>
  </div>
</section>

<section>
  <div class="container">
    <div class="row align-items-center">
      <div class="col-lg-6">
        <div class="p-5">
          <img class="img-fluid rounded-circle" src="images/02.jpg" alt="">
        </div>
      </div>
      <div class="col-lg-6">
        <div class="p-5">
          <h2 class="display-4">We salute you!</h2>
          <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quod aliquid, mollitia odio veniam sit iste esse assumenda amet aperiam exercitationem, ea animi blanditiis recusandae! Ratione voluptatum molestiae adipisci, beatae obcaecati.</p>
        </div>
      </div>
    </div>
  </div>
</section>

<section>
  <div class="container">
    <div class="row align-items-center">
      <div class="col-lg-6 order-lg-2">
        <div class="p-5">
          <img class="img-fluid rounded-circle" src="images/03.jpg" alt="">
        </div>
      </div>
      <div class="col-lg-6 order-lg-1">
        <div class="p-5">
          <h2 class="display-4">Let there be rock!</h2>
          <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quod aliquid, mollitia odio veniam sit iste esse assumenda amet aperiam exercitationem, ea animi blanditiis recusandae! Ratione voluptatum molestiae adipisci, beatae obcaecati.</p>
        </div>
      </div>
    </div>
  </div>
</section>

<!-- Footer -->
<footer class="py-5 bg-black">
  <div class="container">
    <p class="m-0 text-center text-white small">Copyright &copy; Your Website 2019</p>
  </div>
  <!-- /.container -->
</footer>

app/views/shared/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SwishRails</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://fonts.googleapis.com/css?family=Catamaran:700|Lato&display=swap" rel="stylesheet">
    <%= stylesheet_link_tag 'frontend', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'frontend', 'data-turbolinks-track': 'reload' %>

  </head>

  <body>
  <%= render 'shared/layouts/components/navigation' %>
  <%= yield %>
  <% flash.each do |message_type, message| %>
    <div class="alert alert-info alert-dismissible fade show" role="alert">
      <%= message %>
      <button class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
  <% end %>


  </body>
</html>

app/views/shared/layouts/components/_navigation.html.erb
<!-- Navigation -->
<nav class="navbar navbar-expand-lg navbar-dark navbar-custom fixed-top">
  <div class="container">
    <a class="navbar-brand" href="#">Start Bootstrap</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarResponsive">
      <ul class="navbar-nav ml-auto">
        <% if current_user.present? %>
          <li class="nav-item">
            <a class="nav-link" href="/users/edit">Edit Profile</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="/users/swish">My Swishes</a>
          </li>
          <li class="nav-item">
            <%= link_to "Log Out", destroy_user_session_path, method: :delete, class: "nav-link" %>
          </li>
        <% else %>
          <li class="nav-item">
            <a class="nav-link" href="/users/sign_up">Sign Up</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="/users/sign_in">Log In</a>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/users/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SwishRails</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <link href="https://fonts.googleapis.com/css?family=Catamaran:700|Lato&display=swap" rel="stylesheet">
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag 'custom', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag 'swish', 'data-turbolinks-track': 'reload' %>
</head>

<body>
<% if current_user.present? %>
  <nav class="navbar navbar-dark fixed-top bg-primary flex-md-nowrap p-0 shadow">
    <a class="navbar-brand col-sm-3 col-md-2 mr-0" href="#">
      <img src="/images/swish-inverse.png" alt="" width="30" height="30">
      <strong>Swish</strong>
    </a>
    <ul class="navbar-nav px-3">
      <li class="nav-item">

        <a href="<%= new_users_swish_url %>" class="nav-link">
          <i class="fas fa-plus-square"></i>
          Create a New Swish
        </a>

      </li>
    </ul>
    <!--  <input class="form-control form-control-dark w-100" type="text" placeholder="Search" aria-label="Search">-->
    <ul class="navbar-nav px-3">
      <li class="nav-item ">
        <%= link_to('Edit Profile', edit_user_registration_url, class: "nav-link") %>
      </li>
      <li class="nav-item ">
        <%= link_to('Sign Out', destroy_user_session_path, method: :delete, class: "nav-link") %>
      </li>
    </ul>
  </nav>
  <div class="container-fluid">
    <div class="row">
      <nav class="col-md-2 d-none d-md-block bg-light sidebar">
        <div class="sidebar-sticky">
          <ul class="nav flex-column">
            <li class="nav-item">
              <a class="nav-link" href="#">
                <i class="fa fa-chart-line"></i>
                Dashboard
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="<%= users_swish_index_url %>">
                <i class="fa fa-list-ul"></i>
                All Swishes
              </a>
            </li>
            <li class="nav-item">
              <a href="<%= new_users_swish_url %>" class="nav-link">
                <i class="fas fa-plus-square"></i>
                Create a New Swish
              </a>
            </li>

          </ul>


        </div>
      </nav>
<% end %>
<main role="main" class="
  <% if current_user.present? %> col-md-9 ml-sm-auto col-lg-10
  <% end %> px-4">
  <%= yield %>
  <% flash.each do |message_type, message| %>
    <div class="alert alert-warning alert-dismissible fade show" role="alert">
      <%= message %>
      <button class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
  <% end %>

</main>
<% if current_user.present? %>
  </div>
  </div>
<% end %>

</body>
</html>

app/views/users/swish/_swish_report_table.html.erb
<div class="table-responsive">
  <table class="table ">
    <thead >
    <tr>
      <th> Created At</th>
      <th>Accessibility</th>
      <th>Performance</th>
      <th>PWA</th>
      <th>SEO</th>
      <th>Best-Practices</th>
      <th>First Contentful Paint</th>
      <th>First CPU Idle</th>
      <th>First Meaningful Paint</th>
      <th>Estimated Input Latency</th>
      <th>Time To Interactive</th>
      <th>Speed Index</th>
      <th>View Report</th>
    </tr>
    </thead>
    <% swish_reports.each_with_index do |swish_report, index| %>
      <tr>
        <th style="width: 6rem"><%= swish_report.created_at.to_formatted_s(:short) %></th>
        <td>  <%== metric_with_change(swish_report, :accessibility, swish_reports, index) %>     </td>
        <td>  <%== metric_with_change(swish_report, :performance, swish_reports, index) %>  </td>
        <td>  <%== metric_with_change(swish_report, :pwa, swish_reports, index) %>  </td>
        <td>  <%== metric_with_change(swish_report, :seo, swish_reports, index) %>  </td>
        <td>  <%== metric_with_change(swish_report, :best_practices, swish_reports, index) %>  </td>
        <td>  <%== metric_with_change(swish_report, :first_contentful_paint, swish_reports, index) %>

        </td>
        <td>  <%== metric_with_change(swish_report, :first_cpu_idle, swish_reports, index, 's', true) %>

        </td>
        <td>  <%== metric_with_change(swish_report, :first_meaningful_paint, swish_reports, index, 's', true) %>

        </td>
        <td>  <%== metric_with_change(swish_report, :estimated_input_latency, swish_reports, index, 's', true) %>

        </td>
        <td>  <%== metric_with_change(swish_report, :time_to_interactive, swish_reports, index, 's', true) %>

        </td>
        <td>  <%== metric_with_change(swish_report, :speed_index, swish_reports, index, 's', true) %>  </td>
        <td>
          <a href="https://googlechrome.github.io/lighthouse/viewer/?gist=<%= swish_report.gist_id %>" target="_blank">View</a>
        </td>
      </tr>
    <% end %>
  </table>
  <div class="collapse multi-collapse collapse-stats">

    <table class="table table-sm">
      <thead>
      <tr>
        <th> Statistic</th>
        <th>Accessibility</th>
        <th>Performance</th>
        <th>PWA</th>
        <th>SEO</th>
        <th>Best-Practices</th>
        <th>First Contentful Paint</th>
        <th>First CPU Idle</th>
        <th>First Meaningful Paint</th>
        <th>Estimated Input Latency</th>
        <th>Time To Interactive</th>
        <th>Speed Index</th>
      </tr>
      </thead>


      <% swish_reports_description.each do |key, value| %>
        <tr>
          <th>
            <%= key %>
          </th>
          <% value.each do |metric| %>
            <td><%= metric.round(2) %></td>
          <% end %>
        </tr>
      <% end %>
    </table>
  </div>
</div>

app/views/users/swish/index.html.erb
<div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
  <h1 class="h2">All <%= controller_path.split('/').last.to_s.titleize.pluralize %></h1>
</div>
<div class="row">
  <div class="col-md-12">
    <div class="table-responsive">

      <table class="table table-striped table-hover ">

        <thead class="bg-primary text-white ">
        <tr>
          <th>ID</th>
          <th>URL</th>
          <th>Reports</th>
          <th>Created At</th>
        </tr>
        </thead>
        <tbody>
        <% @swishes.each do |swish| %>
          <tr>
            <td>
              <%= link_to "##{swish.id}", users_swish_url(swish), title: "Show Swish" %>
            </td>
            <td>
              <%= swish.url %>
              <a href="<%= swish.url %>" target="_blank" title="Open Link"><i class='fas fa-external-link-alt'></i></a>
            </td>
            <td>
              <%= swish.swish_reports.count %>
            </td>
            <td>
              <%= swish.created_at.to_formatted_s(:long) %>
            </td>
          </tr>
        <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/users/swish/new.html.erb
<div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
  <h1 class="h2"><%= action_name.titleize %> <%= controller_path.split('/').last.to_s.titleize %></h1>
</div>
<div class="row">
  <div class="col-md-12">
    <div id="app">
       <form action="#" @submit.prevent="run">
        <div class="form-group  ">
          <label for="text">URL</label>
          <div class="input-group w-50">
            <input id="text" name="text" placeholder="example.com" type="text" v-model="url" class="form-control form-control-lg">
          </div>
        </div>
        <div class="form-group">
          <button class="btn btn-primary" type="button" disabled v-if="loadingResults">
            <span class="spinner-grow spinner-grow-sm" role="status" aria-hidden="true"></span>
            Loading...
          </button>
          <button name="submit" type="submit" class="btn btn-primary" v-if="!loadingResults">Submit</button>
        </div>
      </form>
      <div class="result" v-show="result != null">

        <h3>Result</h3>
        <div class="notification" id="result"></div>
        <table class="table table-sm w-50 mt-4">
          <tr v-for="(value, metric) in lighthouseMetrics">
            <th>{{ metric }}</th>
            <td> {{ value }}</td>
          </tr>
        </table>

        <p v-show="result != null">
          <button class="btn btn-primary btn-sm" type="button" data-toggle="collapse" data-target="#collapseExample" aria-expanded="false" aria-controls="collapseExample">
            Show Result JSON
          </button>
        </p>
        <div class="collapse" id="collapseExample">
          <div class="preview-json">
            <pre v-html="result"></pre>
          </div>
        </div>

      </div>


    </div>
  </div>
</div>

app/views/users/swish/show.html.erb
<div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
  <h1 class="h2"> Swish "<%= @swish.url %>"
    <small><a href="<%= @swish.url %>" target="_blank" title="Open Link"><i class='fas fa-external-link-alt'></i></a></small>


  </h1>

  <button class="btn btn-primary btn-sm" type="button" data-toggle="collapse" data-target=".collapse-stats" aria-expanded="false" aria-controls="multiCollapseExample1 multiCollapseExample2">Show
    Stats
  </button>

</div>
<div class="row">
  <div class="col-md-12">


    <div id="accordion">
      <% @swish_reports.each_with_index do |(url, swish_reports), index| %>
        <div class="card">
          <div class="card-header p-0" id="headingOne">

            <button class="btn btn-default btn-block text-left" data-toggle="collapse" data-target="#collapse-<%= index + 1 %>" aria-expanded="true" aria-controls="collapse-<%= index + 1 %>">
              Path: <%= URI(url).path == "" ? "/" : URI(url).path %>
              <small class="float-right"><a href="<%= url %>" target="_blank" title="Open Link"><i class='fas fa-external-link-alt'></i></a></small>
            </button>
          </div>

          <div id="collapse-<%= index + 1 %>" class="collapse
            <% if index == 0 %>show
            <% end %>" aria-labelledby="heading-<%= index + 1 %>" data-parent="#accordion">
            <div class="">
              <%= render partial: 'swish_report_table', locals: {swish_reports: swish_reports, swish_reports_description: @swish_reports_description[url]} %>

            </div>
          </div>
        </div>
      <% end %>

    </div>
    <!--    <div class="card ">-->
    <!--      <div class="card-body">-->
    <%#= render partial: 'swish_report_table', locals: {swish_reports: @swish.swish_reports, swish_reports_description: @swish_reports_description} %>
    <!--      </div>-->
    <!--    </div>-->
  </div>
</div>